Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
Dry off!
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
Dry off!
> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
>
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
>
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
>
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
>
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
>
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
5
4
3
2
1
Blastoff!
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
5
4
3
2
1
Blastoff!

Traceback (most recent call last):
  File "/home/user/Datormacibas/tests_200182410_py.py", line 41, in <module>
    for friend in friends:
NameError: name 'friends' is not defined
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
5
4
3
2
1
Blastoff!

Traceback (most recent call last):
  File "/home/user/Datormacibas/tests_200182410_py.py", line 41, in <module>
    for friend in friends:
NameError: name 'friends' is not defined
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========

Traceback (most recent call last):
  File "/home/user/Datormacibas/tests_200182410_py.py", line 41, in <module>
    for friend in friends:
NameError: name 'friends' is not defined
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Happy New Year:', 'Joseph')
('Happy New Year:', 'Glenn')
('Happy New Year:', 'Sally')
Done!
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
Before
9
41
12
3
74
15
After
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
Before
9
41
12
3
74
15
After

Traceback (most recent call last):
  File "/home/user/Datormacibas/tests_200182410_py.py", line 50, in <module>
    largest_so_far
NameError: name 'largest_so_far' is not defined
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========

Traceback (most recent call last):
  File "/home/user/Datormacibas/tests_200182410_py.py", line 50, in <module>
    largest_so_far
NameError: name 'largest_so_far' is not defined
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', -1)
(9, 9)
(41, 41)
(41, 12)
(41, 3)
(74, 74)
(74, 15)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', -1)
(9, 9)
(41, 41)
(41, 12)
(41, 3)
(74, 74)
(74, 15)
('After', 74)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0)
(1, 9)
(2, 41)
(3, 12)
(4, 3)
(5, 74)
(6, 15)
('After', 6)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0)
(9, 9)
(50, 41)
(62, 12)
(65, 3)
(139, 74)
(154, 15)
('After', 154)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0, 0)
(1, 9, 9)
(2, 50, 41)
(3, 62, 12)
(4, 65, 3)
(5, 139, 74)
(6, 154, 15)
('After', 6, 154, 25)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0, 0)
(1, 9, 9)
(2, 50, 41)
(3, 62, 12)
(4, 65, 3)
(5, 139, 74)
(6, 154, 15)
('After', 6, 154, 25)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0, 0)

Traceback (most recent call last):
  File "/home/user/Datormacibas/tests_200182410_py.py", line 76, in <module>
    count = count1
NameError: name 'count1' is not defined
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0, 0)
(1, 9, 9)
(2, 50, 41)
(3, 62, 12)
(4, 65, 3)
(5, 139, 74)
(6, 154, 15)
('After', 6, 154, 25)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0, 0)
(1, 9, 9)
(2, 50, 41)
(3, 62, 12)
(4, 65, 3)
(5, 139, 74)
(6, 154, 15)
('After', 6, 154, 25)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0, 0)
(1, 9, 9)
(2, 50, 41)
(3, 62, 12)
(4, 65, 3)
(5, 139, 74)
(6, 154, 15)
('After', 6, 154, 25)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0, 0)
(1, 9, 9)
(2, 50, 41)
(3, 62, 12)
(4, 65, 3)
(5, 139, 74)
(6, 154, 15)
('After', 6, 154, 25)
Before
After
('Large number', 41)
After
After
After
('Large number', 74)
After
After
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0, 0)
(1, 9, 9)
(2, 50, 41)
(3, 62, 12)
(4, 65, 3)
(5, 139, 74)
(6, 154, 15)
('After', 6, 154, 25)
Before
After
('Large number', 41)
After
After
After
('Large number', 74)
After
After
('Before', False)

Traceback (most recent call last):
  File "/home/user/Datormacibas/tests_200182410_py.py", line 92, in <module>
    print(fouund,value)
NameError: name 'fouund' is not defined
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', 0, 0)
(1, 9, 9)
(2, 50, 41)
(3, 62, 12)
(4, 65, 3)
(5, 139, 74)
(6, 154, 15)
('After', 6, 154, 25)
Before
After
('Large number', 41)
After
After
After
('Large number', 74)
After
After
('Before', False)
(False, 9)
(False, 41)
(False, 12)
(True, 3)
(True, 74)
(True, 15)
('After', True)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', -1)
(9, 9)
(41, 41)
(41, 12)
(41, 3)
(74, 74)
(74, 15)
('After', 74)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
('Before', -1)
(-1, 9)
(-1, 41)
(-1, 12)
(-1, 3)
(-1, 74)
(-1, 15)
('After', -1)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
Before
(9, 9)
(9, 41)
(9, 12)
(3, 3)
(3, 74)
(3, 15)
('After', 3)
>>> 
=========== RESTART: /home/user/Datormacibas/tests_200182410_py.py ===========
Before
(3, 3)
(3, 41)
(3, 12)
(3, 9)
(3, 74)
(3, 15)
('After', 3)
>>> 
